# The Site Configuration
theme: jekyll-theme-chirpy

lang: es
timezone: Europe/Madrid

title: miRdeX-nf
tagline: Documentation
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: "https://antoglz.github.io"
baseurl: "/mirdex_documentation_test" # <-- nombre EXACTO del repo

github:
  username: antoglz

social:
  name: Antonio González Sánchez
  email: antonio.gonzalez.sanchez@csic.es
  links:
    - https://github.com/antoglz

toc: true
theme_mode:

# (Resto igual…)
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

kramdown:
  parse_block_html: true

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
